name: Release Service

on:
  push:
    tags: "3.*"

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*

    - name: Get current time
      uses: MyJetTools/get-current-time@v2
      id: current-time
      with:
        format: YYYY-MM-DD HH:mm:ss
        utcOffset: "+00:00"

    - name: Build
      run: dotnet build --configuration Release /p:AssemblyVersion=${GITHUB_REF#refs/tags/}
    - name: Test
      run: dotnet test --no-build --configuration Release
    - name: ls
      run: ls

    - name: Publish Service
      run: dotnet publish ./DealingAdmin/DealingAdmin.csproj --configuration Release /p:AssemblyVersion=${GITHUB_REF#refs/tags/} --output ./publish-api

    - name: Check Service dir
      run: ls ./publish-api

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/tags/})"
      id: extract_branch


    - name: Publish image Azure
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.ST_DOCKER_USER }}
        password: ${{ secrets.ST_DOCKER_PASSWORD }}
        path: ./publish-api
        registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        repository: margin/dealing.admin
        tag_with_ref: true
        build_args: app_version=dealing.admin:${{ steps.extract_branch.outputs.branch }},app_compilation_date=${{ steps.current-time.outputs.formattedTime }}

  update_version_prod_kube:
    needs: build
    runs-on: self-hosted
    steps:
    - name: change image name in deployment
      uses: actions/checkout@v2
    - run: |
        echo "${{ secrets.KUBE_CONFIG_ST_PROD }}" | base64 --decode > /tmp/config
        export KUBECONFIG=/tmp/config
        kubectl config current-context
        kubectl get nodes
        ls -la
        kubectl set image deployment/dealing-admin-slot-a dealing-admin-slot-a=${{ secrets.AZURE_CONTAINER_REGISTRY }}/margin/dealing.admin:${GITHUB_REF#refs/tags/} --namespace="simple-trading"
        kubectl set image deployment/dealing-admin-slot-b dealing-admin-slot-b=${{ secrets.AZURE_CONTAINER_REGISTRY }}/margin/dealing.admin:${GITHUB_REF#refs/tags/} --namespace="simple-trading"
 

#  update_version_st_kube:
#    needs: build
#    runs-on: self-hosted
#    steps:
#    - name: get uat kube yamls
#      uses: actions/checkout@v2
#      with:
#        repository: MyJetWallet/kubernates-infrastructure
#        ref: uat        
#        token: ${{ secrets.UAT_GIT_TOKEN }}
#    - run: |
#        imagename=margin/dealing.admin:${GITHUB_REF#refs/tags/}
